<span style="color:green; font-size:26px; font-weight:bold;">2. EDA Y LIMPIEZA </span>


________________________________________________________________________________________________________________________________

<span style="color:green; font-size:23px; font-weight:bold;"> Estructura del fichero de microdatos y variables contenidas:  </span>


El fichero incluye un total de <u>5.284 registros (número total de encuestas realizadas) y 45 columnas.</u>

La Encuesta de Bienestar Personal ofrece información detallada y puntual sobre la percepción del bienestar por parte de la población de la C.A. de Euskadi, plasmada en <u>nueve indicadores:</u>
- Satisfacción con la vida
- Valor de la vida
- Satisfacción con el tiempo de ocio
- Satisfacción con la vivienda y el entorno
- Satisfacción con la economía doméstica
- Estado de ánimo
- Relaciones personales
- Confianza en las personas
- Confianza en los poderes públicos

Se incluyen también un conjunto de <u>variables de tipo categórico</u>, relacionadas con características de la población (lugar de residencia, sexo, edad, tipo de familia,...), <u>así como variables que recogen las respuestas dadas por las personas encuestadas que ayudan a entender la situación de la población en términos de bienestar</u> (estado de salud, estado de ánimo,...).

<span style="color:green; font-size:17px; font-weight:bold;"> Target:</span> tomamos como variable que refleja el estado de bienestar general de las personas la variable denominada como SVIDA, que refleja el nivel de satisfacción con la propia vida.
__________________________________________________________________________________________________________________________________________________________________________________

<span style="color:green; font-size:24px; font-weight:bold;">
DATASET A UTILIZAR: 


*FICHERO DE MICRODATOS DE LA ENCUESTA DE BIENESTAR PERSONAL 2024, EUSTAT*</span>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Microdatos_2024.csv", sep = ";") #TENGO QUE INCLUIR DATASET

df

,AENC,NUMC,NIND,ELEP,TH,CAPITAL,SEXO,EDAD,LNAC,NACI,...,CERTZ,SENSE,SVIVENT,SHOGTR,ANIMO,RELPER,CPUBLI,SITEC1,SAPER,RELFA1
0,2024,5964,2,"442,46048",48,9,6,3,1,1,...,7,2,8,8,5,8,6,1,2,1
1,2024,5965,2,"377,37714",48,9,6,6,1,1,...,5,1,8,9,6,8,2,3,1,1
2,2024,5966,3,"614,41942",48,9,1,1,1,1,...,8,1,9,8,8,8,3,3,1,1
3,2024,5968,1,"191,75079",48,9,1,4,1,1,...,8,1,10,7,7,8,4,3,1,1
4,2024,5970,1,"377,37714",48,9,6,6,1,1,...,5,1,9,8,8,8,5,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5279,2024,538,1,"120,19372",1,9,1,4,1,1,...,7,1,8,7,8,8,6,3,1,1
5280,2024,539,1,"52,87739",1,9,6,7,4,1,...,7,3,8,3,6,8,6,1,2,1
5281,2024,541,4,"201,93742",1,9,6,3,5,1,...,5,4,7,5,5,7,5,3,2,1
5282,2024,542,1,"90,91323",1,9,1,5,4,1,...,6,1,8,8,8,8,5,3,2,1
5283,2024,543,1,"67,31247",1,9,6,3,1,1,...,5,2,8,7,4,4,2,1,1,1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5284 entries, 0 to 5283
Data columns (total 45 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   AENC     5284 non-null   int64
 1   NUMC     5284 non-null   int64
 2   NIND     5284 non-null   int64
 3   ELEP     5284 non-null   str
 4   TH       5284 non-null   int64
 5   CAPITAL  5284 non-null   int64
 6   SEXO     5284 non-null   int64
 7   EDAD     5284 non-null   int64
 8   LNAC     5284 non-null   int64
 9   NACI     5284 non-null   int64
 10  NIVI     0 non-null      float64
 11  LEST3    5284 non-null   int64
 12  RELA     5284 non-null   int64
 13  TIPF     5284 non-null   int64
 14  TGRU     5284 non-null   int64
 15  SVIDA    5284 non-null   int64
 16  SRELA    5284 non-null   int64
 17  STGUS    5284 non-null   int64
 18  SECON    5284 non-null   int64
 19  SVIVI    5284 non-null   int64
 20  SZONA    5284 non-null   int64
 21  SRECR    5284 non-null   int64
 22  STRAB    5284 non-null   int64
 23  STIEM    2468 non-null   float64
 24  MERECE   5284 non-null   int64
 25  HABLAR   5284 non-null   int64
 26  AYFAM    5284 non-null   int64
 27  TENSO    5284 non-null   int64
 28  MORAL    5284 non-null   int64
 29  CALMA    5284 non-null   int64
 30  DEPRE    5284 non-null   int64
 31  FELIZ    5284 non-null   int64
 32  CPER     5284 non-null   int64
 33  CPOL     5284 non-null   int64
 34  CJUS     5284 non-null   int64
 35  CERTZ    5284 non-null   int64
 36  SENSE    5284 non-null   int64
 37  SVIVENT  5284 non-null   int64
 38  SHOGTR   5284 non-null   int64
 39  ANIMO    5284 non-null   int64
 40  RELPER   5284 non-null   int64
 41  CPUBLI   5284 non-null   int64
 42  SITEC1   5284 non-null   int64
 43  SAPER    5284 non-null   int64
 44  RELFA1   5284 non-null   int64
dtypes: float64(2), int64(42), str(1)
memory usage: 1.8 MB

In [4]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
AENC,5284.0,NaN,NaN,NaN,2024.0,0.0,2024.0,2024.0,2024.0,2024.0,2024.0
NUMC,5284.0,NaN,NaN,NaN,3739.776306,2165.544455,1.0,1852.75,3738.5,5612.25,7498.0
NIND,5284.0,NaN,NaN,NaN,1.537661,0.804764,1.0,1.0,1.0,2.0,8.0
ELEP,5284,626,"189,07497",120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TH,5284.0,NaN,NaN,NaN,27.478236,19.050649,1.0,20.0,20.0,48.0,48.0
CAPITAL,5284.0,NaN,NaN,NaN,8398.728993,16587.378524,9.0,9.0,9.0,1059.0,48020.0
SEXO,5284.0,NaN,NaN,NaN,3.649508,2.495762,1.0,1.0,6.0,6.0,6.0
EDAD,5284.0,NaN,NaN,NaN,4.64894,1.814499,1.0,3.0,5.0,6.0,7.0
LNAC,5284.0,NaN,NaN,NaN,1.975208,1.515505,1.0,1.0,1.0,4.0,5.0
NACI,5284.0,NaN,NaN,NaN,1.222369,1.030825,1.0,1.0,1.0,1.0,6.0
NIVI,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LEST3,5284.0,NaN,NaN,NaN,1.950227,0.899861,1.0,1.0,2.0,3.0,3.0
RELA,5284.0,NaN,NaN,NaN,2.026495,0.979855,1.0,1.0,2.0,3.0,3.0
TIPF,5284.0,NaN,NaN,NaN,2.874716,1.563778,1.0,1.0,3.0,4.0,7.0
TGRU,5284.0,NaN,NaN,NaN,2.322104,1.240506,1.0,1.0,2.0,3.0,5.0
SVIDA,5284.0,NaN,NaN,NaN,7.313588,1.770229,0.0,7.0,8.0,8.0,10.0
SRELA,5284.0,NaN,NaN,NaN,7.793906,1.698033,0.0,7.0,8.0,9.0,10.0
STGUS,5284.0,NaN,NaN,NaN,6.913134,2.235819,0.0,6.0,7.0,8.0,10.0
SECON,5284.0,NaN,NaN,NaN,6.833838,1.97064,0.0,6.0,7.0,8.0,10.0
SVIVI,5284.0,NaN,NaN,NaN,7.609765,1.832021,0.0,7.0,8.0,9.0,10.0
SZONA,5284.0,NaN,NaN,NaN,7.747729,1.793036,0.0,7.0,8.0,9.0,10.0
SRECR,5284.0,NaN,NaN,NaN,7.593868,1.971136,0.0,7.0,8.0,9.0,10.0
STRAB,5284.0,NaN,NaN,NaN,55.046556,44.83682,0.0,8.0,97.0,97.0,97.0
STIEM,2468.0,NaN,NaN,NaN,10.358185,16.304154,0.0,6.0,8.0,9.0,97.0
MERECE,5284.0,NaN,NaN,NaN,7.626041,1.803999,0.0,7.0,8.0,9.0,10.0
HABLAR,5284.0,NaN,NaN,NaN,1.036715,0.188078,1.0,1.0,1.0,1.0,2.0
AYFAM,5284.0,NaN,NaN,NaN,1.092354,0.536908,1.0,1.0,1.0,1.0,7.0
TENSO,5284.0,NaN,NaN,NaN,3.432627,0.986087,1.0,3.0,3.0,4.0,5.0
MORAL,5284.0,NaN,NaN,NaN,3.922786,1.002788,1.0,3.0,4.0,5.0,5.0
CALMA,5284.0,NaN,NaN,NaN,2.371688,0.814873,1.0,2.0,2.0,3.0,5.0
DEPRE,5284.0,NaN,NaN,NaN,3.872445,0.996875,1.0,3.0,4.0,5.0,5.0
FELIZ,5284.0,NaN,NaN,NaN,2.351817,0.775228,1.0,2.0,2.0,3.0,5.0
CPER,5284.0,NaN,NaN,NaN,6.453255,1.994762,0.0,5.0,7.0,8.0,10.0
CPOL,5284.0,NaN,NaN,NaN,3.513815,2.534486,0.0,1.0,4.0,5.0,10.0
CJUS,5284.0,NaN,NaN,NaN,4.22729,2.471723,0.0,3.0,5.0,6.0,10.0
CERTZ,5284.0,NaN,NaN,NaN,5.74489,2.441832,0.0,5.0,6.0,7.0,10.0
SENSE,5284.0,NaN,NaN,NaN,2.111469,0.898117,1.0,1.0,2.0,3.0,4.0
SVIVENT,5284.0,NaN,NaN,NaN,7.322861,1.419637,1.0,7.0,8.0,8.0,10.0
SHOGTR,5284.0,NaN,NaN,NaN,6.989402,1.812392,0.0,6.0,7.0,8.0,10.0
ANIMO,5284.0,NaN,NaN,NaN,6.411052,1.477396,1.0,5.0,7.0,7.0,9.0
RELPER,5284.0,NaN,NaN,NaN,7.443225,0.922921,1.0,7.0,8.0,8.0,8.0
CPUBLI,5284.0,NaN,NaN,NaN,4.495458,2.048203,0.0,3.0,5.0,6.0,10.0
SITEC1,5284.0,NaN,NaN,NaN,2.328728,0.854556,1.0,1.0,3.0,3.0,3.0
SAPER,5284.0,NaN,NaN,NaN,2.07816,0.767344,1.0,2.0,2.0,2.0,4.0
RELFA1,5284.0,NaN,NaN,NaN,1.221612,0.716678,1.0,1.0,1.0,1.0,4.0