<span style="color:green; font-size:26px; font-weight:bold;">MODELO 3: </span>

<span style="color:green; font-size:33px; font-weight:bold;">DECISION TREE REGRESSOR</span>

________________________________________________________________________________________________________________________________

### Justificación   

Después de utilizar una Regresión Lineal como modelo base, resulta interesante probar un Árbol de Decisión para regresión porque permite capturar relaciones no lineales entre las variables explicativas y la satisfacción con la vida.

A diferencia de la regresión lineal, que asume una relación lineal entre las variables predictoras y la variable objetivo, los árboles de decisión dividen los datos en grupos homogéneos mediante reglas de decisión sucesivas. Esto permite identificar patrones más complejos y posibles interacciones entre variables.

Además, una de sus principales ventajas es la interpretabilidad, ya que las reglas generadas por el árbol pueden visualizarse y analizarse fácilmente. Por ello, este modelo constituye una alternativa interesante para evaluar si existen relaciones no lineales que mejoren la capacidad predictiva respecto a la Regresión Lineal.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

In [56]:
df_modelo = pd.read_csv("../1_Data/processed.csv", sep = ",")

df_modelo

,Terr_hist,Sexo,Edad_interv,Lugar_nacim,Nacionalidad,Nivel_estudios,Actividad,Tipo_hogar,Target_Satisfacc_Vida,Satisf_relac_pers,Sentido_propia_vida,Satisf_econom_domest,Valor_Estado_animo,Satisf_vivienda,Satisf_tiempo_disp,Satisf_viv_y_entorno,Salud_percibida,Confianza_personas,Confianza_poderes_pub
0,48,6,3,1,1,1,1,3,8,8,9,8,5,9,6,8,3,8,6
1,48,6,6,1,1,1,3,3,9,9,10,9,6,9,10,8,4,8,2
2,48,1,1,1,1,3,1,2,8,8,9,8,8,9,8,9,4,6,3
3,48,1,4,1,1,1,1,1,9,9,9,7,7,10,5,10,4,5,4
4,48,6,6,1,1,3,3,3,8,8,10,8,8,9,10,9,3,7,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5279,1,1,4,1,1,2,1,3,7,9,8,7,8,9,8,8,4,6,6
5280,1,6,7,4,1,1,3,1,6,8,7,3,6,7,10,8,3,5,6
5281,1,6,3,5,1,2,3,2,4,5,5,5,5,8,5,7,3,5,5
5282,1,1,5,4,1,1,1,3,8,8,9,8,8,8,7,8,3,7,5
5283,1,6,3,1,1,3,1,1,2,1,5,7,4,8,4,8,4,1,2

In [57]:
df_modelo.info()

<class 'pandas.DataFrame'>
RangeIndex: 5284 entries, 0 to 5283
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Terr_hist              5284 non-null   int64
 1   Sexo                   5284 non-null   int64
 2   Edad_interv            5284 non-null   int64
 3   Lugar_nacim            5284 non-null   int64
 4   Nacionalidad           5284 non-null   int64
 5   Nivel_estudios         5284 non-null   int64
 6   Actividad              5284 non-null   int64
 7   Tipo_hogar             5284 non-null   int64
 8   Target_Satisfacc_Vida  5284 non-null   int64
 9   Satisf_relac_pers      5284 non-null   int64
 10  Sentido_propia_vida    5284 non-null   int64
 11  Satisf_econom_domest   5284 non-null   int64
 12  Valor_Estado_animo     5284 non-null   int64
 13  Satisf_vivienda        5284 non-null   int64
 14  Satisf_tiempo_disp     5284 non-null   int64
 15  Satisf_viv_y_entorno   5284 non-null   int64
 16  Salud_percibida        5284 non-null   int64
 17  Confianza_personas     5284 non-null   int64
 18  Confianza_poderes_pub  5284 non-null   int64
dtypes: int64(19)
memory usage: 784.5 KB

In [58]:
df_modelo.describe(include='all')

,Terr_hist,Sexo,Edad_interv,Lugar_nacim,Nacionalidad,Nivel_estudios,Actividad,Tipo_hogar,Target_Satisfacc_Vida,Satisf_relac_pers,Sentido_propia_vida,Satisf_econom_domest,Valor_Estado_animo,Satisf_vivienda,Satisf_tiempo_disp,Satisf_viv_y_entorno,Salud_percibida,Confianza_personas,Confianza_poderes_pub
count,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000
mean,27.478236,3.649508,4.648940,1.975208,1.222369,1.950227,2.026495,2.322104,7.313588,7.793906,7.626041,6.989402,6.411052,7.609765,6.913134,7.322861,2.921840,6.453255,4.495458
std,19.050649,2.495762,1.814499,1.515505,1.030825,0.899861,0.979855,1.240506,1.770229,1.698033,1.803999,1.812392,1.477396,1.832021,2.235819,1.419637,0.767344,1.994762,2.048203
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,20.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000,7.000000,7.000000,6.000000,5.000000,7.000000,6.000000,7.000000,3.000000,5.000000,3.000000
50%,20.000000,6.000000,5.000000,1.000000,1.000000,2.000000,2.000000,2.000000,8.000000,8.000000,8.000000,7.000000,7.000000,8.000000,7.000000,8.000000,3.000000,7.000000,5.000000
75%,48.000000,6.000000,6.000000,4.000000,1.000000,3.000000,3.000000,3.000000,8.000000,9.000000,9.000000,8.000000,7.000000,9.000000,8.000000,8.000000,3.000000,8.000000,6.000000
max,48.000000,6.000000,7.000000,5.000000,6.000000,3.000000,3.000000,5.000000,10.000000,10.000000,10.000000,10.000000,9.000000,10.000000,10.000000,10.000000,4.000000,10.000000,10.000000

In [59]:
# Separo X e y
# Variables predictoras
X = df_modelo.drop(columns=['Target_Satisfacc_Vida'])

# Variable target
y = df_modelo['Target_Satisfacc_Vida']

print("Dimensiones de X:", X.shape)
print("Dimensiones de y:", y.shape)

Dimensiones de X: (5284, 18)
Dimensiones de y: (5284,)

In [60]:
# Separo en train y test
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=10
)

In [61]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (4227, 18)
X_test: (1057, 18)
y_train: (4227,)
y_test: (1057,)

Con el objetivo de homogeneizar la escala de las variables predictoras, aplico una estandarización mediante StandardScaler. Esta transformación centra cada variable en media cero y desviación típica uno. El escalador se ajusta exclusivamente sobre el conjunto de entrenamiento y posteriormente se aplica al conjunto de prueba.

In [ ]:
# Escalado

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [63]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(4227, 18)
(1057, 18)

In [64]:
pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
).head()

,Terr_hist,Sexo,Edad_interv,Lugar_nacim,Nacionalidad,Nivel_estudios,Actividad,Tipo_hogar,Satisf_relac_pers,Sentido_propia_vida,Satisf_econom_domest,Valor_Estado_animo,Satisf_vivienda,Satisf_tiempo_disp,Satisf_viv_y_entorno,Salud_percibida,Confianza_personas,Confianza_poderes_pub
0,-0.401921,-1.056728,-1.460134,-0.647570,-0.218731,1.160351,-1.042548,-1.064227,1.289451,0.205338,0.012558,1.746520,1.317433,-0.885645,1.891755,0.095529,-0.227972,0.732122
1,-0.401921,0.946317,1.302617,1.325007,-0.218731,-1.062538,0.997188,-1.064227,-2.211947,-2.560637,-1.629167,-2.331104,0.222938,-1.338266,-2.329492,-1.207056,-1.717364,-2.200760
2,-1.402837,-1.056728,-0.355033,-0.647570,-0.218731,0.048907,-1.042548,2.162809,0.122318,-0.901052,0.012558,1.066916,0.770185,-0.885645,1.188214,1.398114,-0.227972,0.243308
3,1.073111,0.946317,-1.460134,-0.647570,-0.218731,1.160351,-1.042548,0.549291,0.705885,-0.347857,0.012558,0.387312,0.222938,0.019595,0.484673,0.095529,1.261420,0.732122
4,-1.402837,0.946317,0.197517,1.325007,-0.218731,-1.062538,0.997188,-1.064227,1.289451,1.311728,0.559800,-0.971896,0.222938,1.377457,0.484673,-1.207056,-0.724436,-0.245505